name: Deploy to s3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    run-on: ubuntu-latest

    setps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configuration AWS Credentials
        uses: aws-actions/configuration-aws-credentials@v4
        with:
          aws-access-key-id: ${{}}
          aws-secret-access-key: ${{}}
          aws-region: eu-west-3

      - name: Sync files to s3
        run: aws s3 sync . s3://mon-portfolio-abdink/ --delete --exclude "git/*" --exclude ".github/*"
